FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install torch==2.0.1+cpu --index-url https://download.pytorch.org/whl/cpu
RUN pip install -r requirements.txt

COPY test-docker.py test-docker.py

EXPOSE 8080

CMD ["python", "-m", "flask", "--app", "test-docker.py", "run", "--host=0.0.0.0", "--port=8080"]
